export const type = Symbol('type')
export const initial = Symbol('default')
export const transform = Symbol('transform')
export const custom = Symbol('custom')
export const required = Symbol('required')
export const rename = Symbol('rename')