export const type = 'QSAPI_type'
export const initial = 'QSAPI_default'
export const transform = 'QSAPI_transform'
export const custom = 'QSAPI_custom'
export const required = 'QSAPI_required'
export const rename = 'QSAPI_rename'